# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ajbeach2/sqsworker
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go get -v -t -d ./...
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: 
          command: |
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            cp coverage.html /tmp/artifacts
      - run: ./cc-test-reporter after-build --exit-code $?
      - run: golint
      - store_artifacts:
          path: /tmp/artifacts
      
